version: "3.9"
services:
  build_yolo_trt:
    build:
      context: .
      dockerfile: ./arm.dockerfile
    volumes:
      - ./data/2022-11-18_640_256/images:/app/images
      - ./trained-inference-models/:/app/trained-inference-models/
      - ./outputs/:/app/outputs/
      - ./build_engine.sh:/app/build_engine.sh
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash /app/build_engine.sh
