version: "3.9"
services:
  build_yolo_trt:
    build:
      context: .
      dockerfile: ./arm.dockerfile
    volumes:
      - ./data/images:/app/images
      - ./trained-inference-models/:/app/trained-inference-models/
      - ./validation/:/app/validation/
      - ./build_engine.sh:/app/build_engine.sh
    environment:
      - MODEL_PATH=/app/trained-inference-models/2022-12-16
      - IM_W=640
      - IM_H=256
    deploy:
        resources:
          reservations:
            devices:
              - driver: nvidia
                count: 1
                capabilities: [gpu]
    command: bash /app/build_engine.sh
